name: Build/release

on:
  push:
    tags:
      - 'SimpleInstaBot/v*'
      - 'instauto/v*'
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      # Windows fix. See https://github.com/actions/checkout/issues/226
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v6

      # todo remove once fixed https://github.com/actions/setup-node/issues/531
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8

      - run: yarn install --immutable
      - run: yarn workspace instauto build

      - run: yarn workspace simpleinstabot build
      - run: yarn workspace simpleinstabot electron-builder
        env:
          GH_TOKEN: ${{ secrets.github_token }}
          # macOS notarization API key
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
